name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: (TEMP) overrule roslib dependency
        run: |
          cd node_modules/roslib
          npm install --save socket.io@^3.0.3
          cd ../..
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
